Vagrant.configure("2") do |config|
  config.vm.box = "super_box"
  config.vm.box_version = "0"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "alice.tp3.b2" do |vm|
    vm.vm.hostname = "alice.tp3.b2"
    vm.vm.network "private_network", type: "static", ip: "10.3.1.11"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "bob.tp3.b2" do |vm|
    vm.vm.hostname = "bob.tp3.b2"
    vm.vm.network "private_network", type: "static", ip: "10.3.1.200"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

  config.vm.define "eve.tp3.b2" do |vm|
    vm.vm.hostname = "eve.tp3.b2"
    vm.vm.network "private_network", type: "static", ip: "10.3.1.57", gateway: nil, dns: nil
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
end
